tecnoalimentos/tecnoalimentos/apps/homepage/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns(
	'tecnoalimentos.apps.homepage.views',
	url(r'^$', 'index', name="homepageindex"),
	url(r'^quienessomos/$', 'aboutus', name="homepageaboutus"),
	url(r'^contacto/$', 'contact', name="homapagecontact"),
	url(r'^productosysoluciones/$', 'products', name="homepageproducts"),
)

tecnoalimentos/tecnoalimentos/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.http import HttpResponse
from sitemaps import StaticViewSitemap
from django.contrib import admin

admin.autodiscover()

sitemaps = {
	'pages': StaticViewSitemap,
}

urlpatterns = patterns('',
	# Examples:
	# url(r'^$', 'tecnoalimentos.views.home', name='home'),
	(r'^tinymce/', include('tinymce.urls')), 
	url(r'^blog/', include('zinnia.urls')),
	url(r'^comments/', include('django.contrib.comments.urls')),	
	url(r'^', include('tecnoalimentos.apps.homepage.urls')),
	(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
	(r'^googlec34fe789f50fc843\.html$', lambda r: HttpResponse("google-site-verification: googlec34fe789f50fc843.html", mimetype="text/plain")),	
	# Uncomment the next line to enable the admin:
	url(r'^admin/', include(admin.site.urls)),
	url(r'^admin/password_reset/$', 'django.contrib.auth.views.password_reset', name='admin_password_reset'),
	(r'^admin/password_reset/done/$', 'django.contrib.auth.views.password_reset_done'),
	(r'^reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm'),
	(r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete'),
)


if settings.DEBUG:
	from django.views.generic import TemplateView
	urlpatterns += patterns(
		'',
		url(r'^404/$', TemplateView.as_view(template_name="404.html")),
		url(r'^403/$', TemplateView.as_view(template_name="403.html")),
		(r'^500/$', TemplateView.as_view(template_name="500.html")),
		(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
	)

tecnoalimentos/tecnoalimentos/apps/homepage/forms.py
#!/usr/local/bin/python
# -*- encoding: utf-8 -*-
from django import forms


class contactForm(forms.Form):
	nombre = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Su nombre'}))
	pais = forms.CharField(widget=forms.TextInput(attrs={'placeholder': u'Ubicación de la empresa'}))
	email = forms.EmailField(widget=forms.TextInput(attrs={'placeholder': 'nick@email.com'}))
	empresa = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Empresa donde trabaja'}))
	telefono = forms.CharField(widget=forms.TextInput(attrs={'placeholder': '58-999-9999999', 'type': 'tel'}))
	texto = forms.CharField(widget=forms.Textarea)

	def clean_asunto(self):
		cd = self.cleaned_data
		asunto = cd.get('asunto')
		if len(asunto) < 3:
			raise forms.ValidationError("El asunto debe tener mas de 2 letras")
		return asunto

	def clean_texto(self):
		cd = self.cleaned_data
		texto = cd.get('texto')
		if len(texto) < 4:
			raise forms.ValidationError("*")
		return texto

tecnoalimentos/tecnoalimentos/apps/homepage/views.py
#!/usr/local/bin/python
# -*- coding: utf-8 -*-
from django.shortcuts import render_to_response
from tecnoalimentos.apps.homepage.forms import contactForm
from django.template import RequestContext
from django.core.mail import send_mail


def index(request):
	return render_to_response('homepage/index.html', context_instance=RequestContext(request))

def aboutus(request):
	return render_to_response('homepage/quienesomos.html', context_instance=RequestContext(request))

def products(request):
	return render_to_response('homepage/products.html', context_instance=RequestContext(request))

def contact(request):
	success = False
	if request.method == 'POST':
		form = contactForm(request.POST)
		if form.is_valid():
			success = True
			cd = form.cleaned_data
			asunto = u'Por: %s mail: %s ' % (cd['nombre'], cd['email'])
			content = u'Email contacto: %s \nNombre: %s \nPais: %s \nEmpresa: %s \nTelefono: %s \nDescripcion: %s' % (cd['email'], cd['nombre'], cd['pais'], cd['empresa'], cd['telefono'], cd['texto'])
			send_mail(asunto, content, 'no-reply@tecnoalimentosam2.com', ['info@tecnoalimentosam2.com'], fail_silently=True)
	else:
		form = contactForm()
	ctx = {'form': form, 'success': success}
	return render_to_response('homepage/contacto.html', ctx, context_instance=RequestContext(request))

tecnoalimentos/tecnoalimentos/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
<!--[if lt IE 8]><script type="text/javascript" src="{{ STATIC_URL }}js/adquiridos/ie6-not-supported.js" ></script><![endif]-->
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<meta name="keywords" content="Materia prima industria alimentica Venezuela granotec tecnoalimentos am2">
<meta name="author" content="duranjo web c.a.">
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
{% block head %} {% endblock%}
<link rel="shortcut icon" type="image/x-icon" href="{{ STATIC_URL }}img/favicon.ico">
<title>{% block title %} {% endblock%}</title>
<link rel="stylesheet" href="{% static 'css/normalize.css' %}">
<link rel="stylesheet" href="{% static 'css/base.css' %}">
<link href='http://fonts.googleapis.com/css?family=Noto+Sans:400,700|Tenor+Sans' rel='stylesheet' type='text/css'>
{% block css %}
{% endblock %}
{% block js %}
{% endblock %}
</head>
<body>
	<!-- Analytics SCRIPT GOOGLE! -->
	<script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	  ga('create', 'UA-54066646-1', 'auto');
	  ga('send', 'pageview');

	</script>
	<header id="home" class="cabecera">
		<div class="wrapper">	
		<div class="logo">
			<img src="{% static 'img/logotecnoalimentos.png' %}" alt="Logo Tecnoalimentos am2">
		</div>					
			<nav class="barraNavegacion">
				{% block navi %}
					<ul>
						<li class="index"><a href="{% url 'homepageindex' %}">Inicio</a></li>
						<li class="index"><a href="{% url 'homepageaboutus' %}">Quiénes Somos</a></li>
						<li class="products"><a href="{% url 'homepageproducts' %}">Productos y Soluciones</a></li>
						<li class="services"><a href="/blog">Blog</a></li>
						<li class="contact"><a href="{% url 'homapagecontact' %}">Contacto</a></li>
					</ul>				
			{% endblock %}
			</nav>
		</div>
	</header>
	<section class="contenido">
		{% block contenido %} {% endblock%}
	</section>
	{% block clear %} {% endblock %}
	<footer>
		{% block footer %}{% endblock%}
		<div class="footerarriba">	
			<div class="wrapper">		
				<ul class="menufooter">
					<li><a href="{% url 'homepageindex' %}">Inicio</a></li>
					<li><a href="{% url 'homepageaboutus' %}">Quienes Somos</a></li>
					<li><a href="{% url 'homepageproducts' %}">Productos y Soluciones</a></li>
					<li><a href="/blog">Blog</a></li>
					<li><a href="{% url 'homapagecontact' %}">Contacto</a></li>
				</ul>
			</div>	
		</div>
		<div class="wrapper">	
			<div class="footermedio">	
					<div class="columna">
						<div class="telefono">+58-424 6441619  / +58-261 3260622</div>
						<div class="email">info@tecnoalimentosam2.com</div>
						<div class="direccion">Maracaibo, Edo. Zulia. Venezuela.</div>
					</div>				
					<div class="columna logofooter">
						<img src="{% static 'img/logotecnoalimentos.png' %}" alt="Logo Tecnoalimentos am2">
					</div>		
				<div class="columna redes">
					<a href="https://twitter.com/"><div class="twitterlogo"></div></a>
					<a href="https://www.facebook.com/"><div class="facebook"></div></a>
					<a href="#"><div class="googleplus"></div></a>
					<a href="http://www.linkedin.com/"><div class="linkedin"></div></a>
					<p>J-31230199-6</p>
				</div>								
			</div>	
			<div class="copyright">
				Tecnoalimentos AM2 © Copyright 2014. Todos los derechos reservados. Developed by: <a href="http://duranjo.com/" rel="nofollow"><img src="http://duranjo.com/static/img/logoduranjo.png" alt="Logo empresa duranjo"/></a>
			</div>

		</div>	  
	</footer>
</body>
</html>

tecnoalimentos/tecnoalimentos/templates/homepage/contacto.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
Contacto - Tecnoalimentos AM2
{% endblock %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/homepage/contacto.css' %}">
{% endblock %}
{% block js %}
<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script type="text/javascript" src="{% static 'js/propios/selectable.js' %}"></script>
{% endblock %}
{% block contenido %}
<section class="contacto">
	<img src="{% static 'img/contactoportada.jpg' %}" class="portada" alt="proveemos materia prima"/>
	<div class="wrapper">
		<div class="titulo2">
			<div class="icono"></div>
			<h2>Contacto</h2>
		</div>	
		{% if success %}
		<div class="mensajeenviado">
			<div class="enviado">Su mensaje ha sido enviado correctamente, pronto nos pondremos en contacto con usted.</div>
			<img class="sobre" src="{{ STATIC_URL }}img/sobre.png" alt="formulario de contacto">	
		</div>
		{% else %}
		{% if form.errors %}
        <p>
            Por favor corregir los errores debajo.
        </p>
   		{% endif %}
   		<div class="cuadroverde">
		<form class="contactoform" action="#" method="POST">
			{% csrf_token %}
			<div class="contactoizquierda">
				<div class="campo">
					{{ field.errors }}
					<label for="nombre">Nombre:</label>
					{{ form.nombre }}
					{{ form.nombre.errors }}
				</div>
				<div class="campo">				
					{{ field.errors }}
					<label for="email">Correo Electrónico:</label>
					{{ form.email }}
					{{ form.email.errors }}
				</div>
				<div class="campo">
					{{ field.errors }}
					<label for="telefono">Teléfono:</label>
					{{ form.telefono }}
					{{ form.telefono.errors }}
				</div>
				<div class="campo">
					{{ field.errors }}
					<label for="id_empresa">Empresa:</label>
					{{ form.empresa }}
					{{ form.empresa.errors }}
				</div>
			</div>
			<div class="contactoderecha">
				<div class="campo">
					{{ field.errors }}
					<label for="id_pais">Pais:</label>
					{{ form.pais }}
					{{ form.pais.errors }}
				</div>
				<div class="textareaDescripcion">
					{{ field.errors }}
					<label for="texto">Mensaje: </label>
					{{ form.texto }}
					{{ form.texto.errors }}
			</div>
			<div class="botonEnviar">
				<input type="submit">
			</div>
		</form>
		{% endif %}
	</div>
		<div class="direccioncontact">
			<p>Dirección: CTRA KM 7 vía el Mojan Local NRO 11721000 sector Zona Industrial Norte. Maracaibo Zulia zona postal 4005</p>
		</div>	
	</section>
	<!-- FACEBOOK SCRIPT -->
			<div id="fb-root"></div>
		<script>(function(d, s, id) {
		  var js, fjs = d.getElementsByTagName(s)[0];
		  if (d.getElementById(id)) return;
		  js = d.createElement(s); js.id = id;
		  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
		  fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));</script>
	<!-- TWITTER SCRIPT -->
	<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
{% endblock%}

tecnoalimentos/tecnoalimentos/templates/homepage/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}
TECNOALIMENTOS AM2
{% endblock%}
{% block head %} 
<meta name="description" content="Tecnoalimentos AM2, C.A. es un confiable proveedor de materias primas para la industria de alimentos de Venezuela con el respaldo y representación exclusiva de firmas de primera línea.">
{% endblock%}
{% block css%}
<link rel="stylesheet" href="{{ STATIC_URL }}css/index.css">
<link rel="stylesheet" href="{% static 'css/flexslider.css' %}">
<link rel="stylesheet" href="{% static 'css/homepage/index.css' %}">
<link href='http://fonts.googleapis.com/css?family=Ubuntu+Condensed' rel='stylesheet' type='text/css'>
{% endblock %}
{% block js %}
<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script type="text/javascript" src="{% static 'js/adquiridos/jquery.flexslider-min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/adquiridos/back-top.js' %}"></script>


{% endblock %}
{% block clear %}{% endblock%}
{% block contenido %}
	<section class="bannerPrincipal">
		<div class="sliderPosition">
			<div class="flexslider">
				<ul class="slides">
					<li>
						<p class="flex-caption">Somos Proveedores de materia prima de la más alta calidad</p>
						<img src="{% static 'img/portada.jpg' %}" alt="proveemos materia prima"/>
						<p class="rifslider">J-31230199-6</p>
					</li>
					<li>
						<p class="flex-caption">Somos Proveedores de materia prima de la más alta calidad</p>
						<img src="{% static 'img/portada3.jpg' %}" alt="proveemos materia prima"/>
						<p class="rifslider">J-31230199-6</p>
					</li>
					<li>
						<p class="flex-caption">Somos Proveedores de materia prima de la más alta calidad</p>
						<img src="{% static 'img/portada4.jpg' %}" alt="proveemos materia prima"/>
						<p class="rifslider">J-31230199-6</p>
					</li>	
					<li>
						<p class="flex-caption">Somos Proveedores de materia prima de la más alta calidad</p>
						<img src="{% static 'img/portada5.jpg' %}" alt="proveemos materia prima"/>
						<p class="rifslider">J-31230199-6</p>
					</li>															
			 	</ul>
			</div>		
		</div>
	</section>
	<section class="aboutus">
		<div class="wrapper">	
			<div class="titulo2">
				<div class="icono"></div>
				<h2>Sobre Tecnoalimentos AM2</h2>
			</div>		
		<div class="intro">
			<p>Considerando las particularidades y especiales características que actualmente rigen el país, Tecnoalimentos AM2, C.A. se ha diferenciado por crear y aperturar espacios de oportunidades  para lograr abastecer y convertirnos en un aliado para las industrias, afianzándonos como un confiable proveedor de materias primas alimenticias con el respaldo y representación exclusiva de firmas de primera línea.</p>
		</div>
			<div class="greenbox">
				<p>"Nuestro trabajo se basa en no vender productos, sino ayudar a obtener el mejor beneficio en su compra..."</p>
			</div>		
	</section>

	<section class="proveedor">
		<div class="wrapper">
			<div class="whitebox">
				<p>Somos Representantes autorizados de </p>
				<a href="http://www.granotec.com/" target="_blank"><img src="{% static 'img/granoteclogo.png' %}" alt="proveemos materia prima"/></a>
			</div>
		</div>	
	</section>
	<section class="productos">
		<div class="wrapper">
			<div class="titulo2">
				<div class="icono"></div>
			</div>	
			<div class="titulo2">
				<h2>Industrias Alimenticias</h2>
				<p>Ofrecemos productos y servicios a las distintas industrias alimenticias</p>
				<div class="industria">
					<img src="{% static 'img/molineria.png' %}" alt="proveemos materia prima"/>
					<h3>Panificación y Molinería</h3>
				</div>
				<div class="industria">
					<img src="{% static 'img/lactea.png' %}" alt="proveemos materia prima"/>
					<h3>Lácteos</h3>
				</div>
				<div class="industria">
					<img src="{% static 'img/carnico.png' %}" alt="proveemos materia prima"/>
					<h3>Cárnicos</h3>
				</div>	
				<div class="industria">
					<img src="{% static 'img/bebidas2.png' %}" alt="proveemos materia prima"/>
					<h3>Bebidas</h3>
				</div>	
				<a class="boton" href="#">Conocer Productos</a>							
			</div>			
		</div>
	</section>
	<section class="filosofia">
		<div class="wrapper">
			<div class="whitebox">
				<p class="filosofiatit">Nuestra Filosofía</p>
				<p class="filosofiasubtit" >En Tecnoalimentos AM2, C.A</p>
				<p class="filosofiatxt">Es que nuestros clientes logren el máximo aprovechamiento de sus requerimientos en soluciones de abastecimiento para su industria, por esta razón hacemos especial énfasis en conocer personalmente sus necesidades y presentarle soluciones y alternativas que logren maximizar los resultados de su gestión. </p>
			</div>
		</div>	
	</section>		
	<section class="clientes">
		<div class="wrapper">
			<div class="titulo2">
				<div class="icono"></div>
				<h2>Clientes de Tecnoalimentos AM2</h2>
				<div class="ccolum">
					<img src="{% static 'img/monaca.jpg' %}" alt="Logo Monaca"/>
					<img src="{% static 'img/alfonsorivas.jpg' %}" alt="logo alfonso rivas"/>
				</div>
				<div class="ccolum">
					<img src="{% static 'img/zulimilk.jpg' %}" alt="logo zulimilk"/>
					<img src="{% static 'img/disbelca.jpg' %}" alt="logo disbelca"/>
				</div>
				<div class="ccolum">
					<img src="{% static 'img/genica.jpg' %}" alt="logo genica"/>
					<img src="{% static 'img/afilca.jpg' %}" alt="logo dafilca"/>
				</div>
			</div>	
		</div>	
	</section>	
	<!-- SLIDER INIT -->
	<script>
		$(document).ready(function() {
		  $('.flexslider').flexslider({
		  	slideshowSpeed: 3400,
		  	// start: function(slider) {
			//        slider.flexAnimate(slider.getTarget("next"));
			//  }
		  });
		});
	</script>
	<!-- Google+ SCRIPT --> 
		<!-- Place this tag after the last badge tag. -->
		<script  async type="text/javascript">
		 window.___gcfg = {lang: 'es-419'};
		 (function() {
		    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
		   po.src = 'https://apis.google.com/js/plusone.js';
		    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
		  })();
		</script>
	<!-- FACEBOOK SCRIPT -->
			<div id="fb-root"></div>
		<script async>(function(d, s, id) {
		  var js, fjs = d.getElementsByTagName(s)[0];
		  if (d.getElementById(id)) return;
		  js = d.createElement(s); js.id = id;
		  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&status=0";
		  fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));</script>
	<!-- TWITTER SCRIPT -->
	<script async>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
	
	<!-- BACK TOP BOX 
	<div id="back-top" class="back-top">
		<a href="#home"><span>↑</span>Regresar arriba</a>
	</div>-->
{% endblock%}

tecnoalimentos/tecnoalimentos/templates/homepage/products.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
Productos y Soluciones Tecnoalimentos
{% endblock %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/homepage/products.css' %}">
{% endblock %}
{% block js %}
<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
{% endblock %}
{% block contenido %}
<section class="productos">
	<img src="{% static 'img/portadaproducto.jpg' %}" class="portada" alt="proveemos materia prima"/>
	<div class="wrapper">
		<div class="titulo2">
			<div class="icono"></div>
			<h2>Productos y Soluciones</h2>
		</div>	
	</div>		
		<div class="wrapper">
			<div class="lineasdecolores">
				<div class="linea verde"></div>
				<div class="linea gris"></div>
				<div class="linea verdeclaro"></div>
			</div>
			<h3> Materias Primas para la Industria de Alimentos</h3>
			<div class="lineasdecolores">
				<div class="linea verde"></div>
				<div class="linea gris"></div>	
				<div class="linea verdeclaro"></div>
			</div>	
			<h4> Proveemos soluciones a las industrias de:</h4>	
				<div class="industria">
					<img src="{% static 'img/molineria.png' %}" alt="proveemos materia prima"/>
					<p>Panificación y Molinería</p>
				</div>
				<div class="industria">
					<img src="{% static 'img/lactea.png' %}" alt="proveemos materia prima"/>
					<p>Lácteos</p>
				</div>
				<div class="industria">
					<img src="{% static 'img/carnico.png' %}" alt="proveemos materia prima"/>
					<p>Cárnicos</p>
				</div>	
				<div class="industria">
					<img src="{% static 'img/bebidas2.png' %}" alt="proveemos materia prima"/>
					<p>Bebidas</p>
				</div>
				<h4>Nuestra Lista de Productos Incluyen:</h4>
				<div class="columnal">
					<ul>
						<li>Mezclas de Polvos Alimenticios y Mejoradores para Harinas</li>
						<li>Alimentos base para Cereales</li>
						<li>Bebidas Lácteas</li>
					</ul>
				</div>	
				<div class="columnal">
					<ul>
						<li>Mezclas a base de vitaminas, proteínas y minerales</li>
						<li>Gelatinas</li>
						<li>Pudines</li>
					</ul>
				</div>						
				<div class="columnal">
					<ul>
						<li>Núcleos y Bloques Vitamínicos</li>
						<li>Materias primas para procesos Lácteos</li>
						<li>Quesos, Yogurt, Mantequilla, Sueros lácteos</li>
					</ul>
				</div>										
			</div>				
		</div>
</section>
{% endblock%}

tecnoalimentos/tecnoalimentos/templates/homepage/quienesomos.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
Sobre Tecnoalimentos AM2
{% endblock %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/homepage/quienesomos.css' %}">
{% endblock %}
{% block js %}
<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
{% endblock %}
{% block contenido %}
<section class="quienessomos">
	<img src="{% static 'img/portadaquienes.jpg' %}" class="portada" alt="proveemos materia prima"/>
		<div class="wrapper">
		<div class="titulo2">
			<div class="icono"></div>
			<h2>Sobre Tecnoalimentos AM2</h2>
		</div>
			<div class="cuadroverde primero">
				<div class="mision">
					<div class="izquierda">
						<img src="{% static 'img/mision.png' %}" alt="proveemos materia prima"/>
						<h3>Misión</h3>
						<div class="lineaverde"></div>
					</div>
					<div class="derecha">
						<p>Tecnoalimentos AM2 C,A. tiene la misión de proveer soluciones integrales adecuadas a las necesidades de nuestros Clientes en diferentes disciplinas en cuanto a requerimientos de Productos,  Materias Primas y Servicios Industriales de la más alta calidad. </p>
					</div>				
				</div>
			</div>
			<div class="cuadroverde">
				<div class="vision">
					<div class="izquierda">
						<p>Ofrecer productos, aditivos y materias primas de la mejor calidad para abastecer las cadenas de producción de alimentos de manera segura y confiable a la población.</p>
					</div>
					<div class="derecha">
						<img src="{% static 'img/vision.png' %}" alt="proveemos materia prima"/>
						<h3>Visión</h3>
						<div class="lineaverde"></div>
					</div>				
				</div>
			</div>
			<div class="cuadroverde">
				<div class="valores">
					<div class="izquierda">
						<img src="{% static 'img/valores.png' %}" alt="proveemos materia prima"/>
						<h3>Valores</h3>
						<div class="lineaverde"></div>
					</div>
					<div class="derecha">
						<p>Entre los valores presentes en nuestra institución con los Clientes y con las Empresas representadas podemos mencionar:</p>
						<ul class="valoreslist">
							<li> <span>Respeto</span></li>
							<li> <span>Honestidad </span></li>
							<li> <span>Lealtad</span></li>
							<li> <span>Compromiso</span></li>
							<li> <span>Profesionalismo</span></li>							
						</ul>
					</div>				
				</div>	
			</div>						
		</div>
</section>
{% endblock%}

tecnoalimentos/tecnoalimentos/templates/homepage/seccionlibre.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
Trabajos realizados - Duranjo
{% endblock %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/seccionlibre.css' %}">
{% endblock %}
{% block js %}
<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
{% endblock %}
{% block contenido %}
<section class="quienessomos">
	<div class="wrapper">
		<div class="tituloStyle"><h2>libre</h2></div>
	</div>
</section>
{% endblock%}

tecnoalimentos/tecnoalimentos/templates/zinnia/_entry_detail.html
{% extends "zinnia/_entry_detail_base.html" %}

tecnoalimentos/tecnoalimentos/templates/zinnia/tags/archives_entries_link.html
{% load i18n %}{% load url from future %}
{% for date in archives %}<link rel="archives" title="{% trans "Archives" %} {{ date|date:"YEAR_MONTH_FORMAT" }}" href="{% url 'zinnia_entry_archive_month' date|date:"Y" date|date:"m" %}" />
{% endfor %}